settings:
  legacy:
    force: false
    interval: 0s
server:
  status: true
  open: false
  port: 8080
  host: localhost
schema:
  - name: youtube-manager-go
    path: .
    commands: {}
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
        - .history
